[package]
authors = ["Jorge Aparicio <jorge@japaric.io>"]
build = "build.rs"
description = "Ergonomic, checked cast functions for primitive types"
documentation = "https://docs.rs/cast"
keywords = ["checked", "cast", "primitive", "integer", "float"]
license = "MIT OR Apache-2.0"
name = "cast"
repository = "https://github.com/japaric/cast.rs"
version = "0.2.7"
edition = "2018"

[features]
# Assume we should use `std` unless asked to do otherwise.
default = ["std"]
# Enable this to get a std::error::Error impl for convenient use with other
# libraries.
std = []
# Enable this for i128/u128 support
x128 = []

[build-dependencies]
rustc_version = "0.4.0"

[dev-dependencies]
quickcheck = "0.9.0"
