on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

name: Continuous integration

jobs:
   test :
    name: Test Suite
    runs-on: ubuntu-latest

    strategy:
      matrix:
        rust:
          - 1.13.0 # MSRV
          - stable
        target:
          - x86_64-unknown-linux-gnu
        include:
          - rust: stable
            target: i686-unknown-linux-musl

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.target }}
          override: true

      - uses: actions-rs/cargo@v1
        if: matrix.rust != 'stable'
        with:
          command: build
          args: --target ${{ matrix.target }}

      - uses: actions-rs/cargo@v1
        if: matrix.rust == 'stable'
        with:
          command: test
          args: --target ${{ matrix.target }}

      - uses: actions-rs/cargo@v1
        if: matrix.rust == 'stable'
        with:
          command: test
          args: --target ${{ matrix.target }} --no-default-features

      - uses: actions-rs/cargo@v1
        if: matrix.rust == 'stable'
        with:
          command: test
          args: --target ${{ matrix.target }} --features x128
